import "server-only";
import { withDatabase } from "@/lib/database";

type Row = Record<string, unknown>;
const all=(sql:string,...params:unknown[])=>withDatabase(db=>db.prepare(sql).all(...params) as Row[]);
const one=(sql:string,...params:unknown[])=>withDatabase(db=>db.prepare(sql).get(...params) as Row|undefined);
const n=(v:unknown)=>Number(v??0);
const round10=(v:number)=>Math.round(v/10)*10;

export type BillingRates={
  pensionRate:number; healthRate:number; longTermCareRate:number; employmentRate:number; industrialAccidentRate:number;
  wageClaimRate:number; asbestosReliefRate:number; disabilityRate:number; localBusinessTaxRate:number; welfareRate:number;
  accidentReserveRate:number; managementFeeRate:number; profitRate:number; vatRate:number;
};

export function calculateBilling(gross:number,r:BillingRates,oneTimeCost=0,manualAdjustment=0){
  const pension=round10(gross*r.pensionRate);
  const health=round10(gross*r.healthRate);
  const longTermCare=round10(health*r.longTermCareRate);
  const employment=round10(gross*r.employmentRate);
  const industrialAccident=round10(gross*r.industrialAccidentRate);
  const wageClaim=round10(gross*r.wageClaimRate);
  const asbestosRelief=round10(gross*r.asbestosReliefRate);
  const disability=round10(gross*r.disabilityRate);
  const localBusinessTax=round10(gross*r.localBusinessTaxRate);
  const welfare=round10(gross*r.welfareRate);
  const accidentReserve=round10(gross*r.accidentReserveRate);
  const directAndIndirect=gross+pension+health+longTermCare+employment+industrialAccident+wageClaim+asbestosRelief+disability+localBusinessTax+welfare+accidentReserve;
  const managementFee=round10(directAndIndirect*r.managementFeeRate);
  const profit=round10((directAndIndirect+managementFee)*r.profitRate);
  const supplyAmount=round10(directAndIndirect+managementFee+profit+oneTimeCost+manualAdjustment);
  const vat=Math.trunc(supplyAmount*r.vatRate);
  return {pension,health,longTermCare,employment,industrialAccident,wageClaim,asbestosRelief,disability,localBusinessTax,welfare,accidentReserve,managementFee,profit,supplyAmount,vat,totalAmount:supplyAmount+vat};
}

export function listBillingRules(){return all("SELECT * FROM app_billing_rule_versions ORDER BY effective_from DESC,id DESC");}
export function listBillingRuns(){return all(`SELECT r.*,br.name rule_name,COUNT(i.id) item_count,COALESCE(SUM(i.total_amount),0) total_amount,SUM(CASE WHEN i.review_status='확인필요' THEN 1 ELSE 0 END) review_count FROM app_billing_runs r JOIN app_billing_rule_versions br ON br.id=r.billing_rule_id LEFT JOIN app_billing_items i ON i.billing_run_id=r.id GROUP BY r.id ORDER BY r.billing_month DESC`);}
export function getBillingRun(id:number){const run=one(`SELECT r.*,br.name rule_name FROM app_billing_runs r JOIN app_billing_rule_versions br ON br.id=r.billing_rule_id WHERE r.id=?`,id); if(!run)return null; const items=all(`SELECT i.*,w.name worker_name,w.employee_no,s.name site_name,j.name job_name FROM app_billing_items i JOIN app_workers w ON w.id=i.worker_id LEFT JOIN app_assignments a ON a.id=i.assignment_id LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id WHERE i.billing_run_id=? ORDER BY s.name,w.name`,id); return {run,items};}

export function createBillingRule(values:Record<string,unknown>){return withDatabase(db=>{const r=db.prepare(`INSERT INTO app_billing_rule_versions(name,effective_from,effective_to,pension_rate,health_rate,long_term_care_rate,employment_rate,industrial_accident_rate,wage_claim_rate,asbestos_relief_rate,disability_rate,local_business_tax_rate,welfare_rate,accident_reserve_rate,management_fee_rate,profit_rate,vat_rate,review_status,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(values.name,values.effective_from,values.effective_to||null,n(values.pension_rate),n(values.health_rate),n(values.long_term_care_rate),n(values.employment_rate),n(values.industrial_accident_rate),n(values.wage_claim_rate),n(values.asbestos_relief_rate),n(values.disability_rate),n(values.local_business_tax_rate),n(values.welfare_rate),n(values.accident_reserve_rate),n(values.management_fee_rate),n(values.profit_rate),n(values.vat_rate)||0.1,values.review_status||"검토",values.note||null); db.prepare("INSERT INTO app_audit_logs(action,entity_type,entity_id,summary) VALUES('create','billing_rule',?,'청구 기준 등록')").run(r.lastInsertRowid); return Number(r.lastInsertRowid);});}

export function generateBillingRun(month:string,ruleId:number,note?:string){return withDatabase(db=>{const exists=db.prepare("SELECT id FROM app_billing_runs WHERE billing_month=?").get(month) as Row|undefined;if(exists)return Number(exists.id);const payroll=db.prepare("SELECT * FROM app_payroll_runs WHERE payroll_month=?").get(month) as Row|undefined;if(!payroll||!["승인","마감"].includes(String(payroll.status)))throw new Error("승인 또는 마감된 급여회차가 먼저 필요합니다.");const rule=db.prepare("SELECT * FROM app_billing_rule_versions WHERE id=?").get(ruleId) as Row|undefined;if(!rule||rule.review_status!=="확정")throw new Error("확정된 청구 기준만 사용할 수 있습니다.");const runResult=db.prepare("INSERT INTO app_billing_runs(billing_month,payroll_run_id,billing_rule_id,note) VALUES(?,?,?,?)").run(month,payroll.id,ruleId,note||null);const runId=Number(runResult.lastInsertRowid);const rates:BillingRates={pensionRate:n(rule.pension_rate),healthRate:n(rule.health_rate),longTermCareRate:n(rule.long_term_care_rate),employmentRate:n(rule.employment_rate),industrialAccidentRate:n(rule.industrial_accident_rate),wageClaimRate:n(rule.wage_claim_rate),asbestosReliefRate:n(rule.asbestos_relief_rate),disabilityRate:n(rule.disability_rate),localBusinessTaxRate:n(rule.local_business_tax_rate),welfareRate:n(rule.welfare_rate),accidentReserveRate:n(rule.accident_reserve_rate),managementFeeRate:n(rule.management_fee_rate),profitRate:n(rule.profit_rate),vatRate:n(rule.vat_rate)};const payrollItems=db.prepare("SELECT * FROM app_payroll_items WHERE payroll_run_id=?").all(payroll.id) as Row[];const ins=db.prepare(`INSERT INTO app_billing_items(billing_run_id,payroll_item_id,worker_id,assignment_id,payroll_gross,pension,health,long_term_care,employment,industrial_accident,wage_claim,asbestos_relief,disability,local_business_tax,welfare,accident_reserve,management_fee,profit,supply_amount,vat,total_amount,calculation_json,review_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);for(const p of payrollItems){const c=calculateBilling(n(p.gross_pay),rates);ins.run(runId,p.id,p.worker_id,p.assignment_id,n(p.gross_pay),c.pension,c.health,c.longTermCare,c.employment,c.industrialAccident,c.wageClaim,c.asbestosRelief,c.disability,c.localBusinessTax,c.welfare,c.accidentReserve,c.managementFee,c.profit,c.supplyAmount,c.vat,c.totalAmount,JSON.stringify({ruleId,rates}),p.review_status==="정상"?"정상":"확인필요");}db.prepare("INSERT INTO app_audit_logs(action,entity_type,entity_id,summary) VALUES('create','billing_run',?,?)").run(runId,`${month} 청구회차 생성`);return runId;});}

export function updateBillingItem(id:number,oneTimeCost:number,manualAdjustment:number,manualReason:string){return withDatabase(db=>{const item=db.prepare("SELECT * FROM app_billing_items WHERE id=?").get(id) as Row|undefined;if(!item)throw new Error("청구 항목을 찾을 수 없습니다.");const run=db.prepare("SELECT * FROM app_billing_runs WHERE id=?").get(item.billing_run_id) as Row;if(run.status==="마감")throw new Error("마감된 청구는 수정할 수 없습니다.");const rule=db.prepare("SELECT * FROM app_billing_rule_versions WHERE id=?").get(run.billing_rule_id) as Row;const rates:BillingRates={pensionRate:n(rule.pension_rate),healthRate:n(rule.health_rate),longTermCareRate:n(rule.long_term_care_rate),employmentRate:n(rule.employment_rate),industrialAccidentRate:n(rule.industrial_accident_rate),wageClaimRate:n(rule.wage_claim_rate),asbestosReliefRate:n(rule.asbestos_relief_rate),disabilityRate:n(rule.disability_rate),localBusinessTaxRate:n(rule.local_business_tax_rate),welfareRate:n(rule.welfare_rate),accidentReserveRate:n(rule.accident_reserve_rate),managementFeeRate:n(rule.management_fee_rate),profitRate:n(rule.profit_rate),vatRate:n(rule.vat_rate)};const c=calculateBilling(n(item.payroll_gross),rates,oneTimeCost,manualAdjustment);const review=manualAdjustment!==0&&!manualReason.trim()?"확인필요":"정상";db.prepare(`UPDATE app_billing_items SET one_time_cost=?,manual_adjustment=?,manual_reason=?,pension=?,health=?,long_term_care=?,employment=?,industrial_accident=?,wage_claim=?,asbestos_relief=?,disability=?,local_business_tax=?,welfare=?,accident_reserve=?,management_fee=?,profit=?,supply_amount=?,vat=?,total_amount=?,review_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(oneTimeCost,manualAdjustment,manualReason||null,c.pension,c.health,c.longTermCare,c.employment,c.industrialAccident,c.wageClaim,c.asbestosRelief,c.disability,c.localBusinessTax,c.welfare,c.accidentReserve,c.managementFee,c.profit,c.supplyAmount,c.vat,c.totalAmount,review,id);return Number(item.billing_run_id);});}

export function changeBillingStatus(id:number,status:"작성중"|"검토"|"승인"|"마감"){withDatabase(db=>{if(["승인","마감"].includes(status)){const p=db.prepare("SELECT COUNT(*) count FROM app_billing_items WHERE billing_run_id=? AND review_status='확인필요'").get(id) as Row;if(n(p.count)>0)throw new Error("확인필요 청구가 남아 있습니다.");}db.prepare(`UPDATE app_billing_runs SET status=?,approved_at=CASE WHEN ?='승인' THEN CURRENT_TIMESTAMP ELSE approved_at END,closed_at=CASE WHEN ?='마감' THEN CURRENT_TIMESTAMP ELSE closed_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(status,status,status,id);});}
