import "server-only";
import { withDatabase } from "@/lib/database";

type Row=Record<string,unknown>;
const v=(x:unknown)=>String(x??"");
const escapeHtml=(value:unknown)=>v(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
export function listDocumentTemplates(){return withDatabase(db=>db.prepare("SELECT * FROM app_document_templates WHERE is_active=1 ORDER BY document_type,name").all() as Row[]);}
export function listGeneratedDocuments(limit=100){return withDatabase(db=>db.prepare(`SELECT d.*,w.name worker_name,t.name template_name,u.display_name generated_by FROM app_generated_documents d JOIN app_workers w ON w.id=d.worker_id JOIN app_document_templates t ON t.id=d.template_id LEFT JOIN app_users u ON u.id=d.generated_by_user_id ORDER BY d.id DESC LIMIT ?`).all(limit) as Row[]);}
export function getGeneratedDocument(id:number){return withDatabase(db=>db.prepare(`SELECT d.*,w.name worker_name,t.name template_name FROM app_generated_documents d JOIN app_workers w ON w.id=d.worker_id JOIN app_document_templates t ON t.id=d.template_id WHERE d.id=?`).get(id) as Row|undefined);}
export function documentWorkerOptions(){return withDatabase(db=>db.prepare("SELECT id,name,employee_no,status FROM app_workers ORDER BY CASE status WHEN '재직' THEN 0 WHEN '입사예정' THEN 1 ELSE 2 END,name").all() as Row[]);}
export function generateDocument(templateId:number,workerId:number,userId:number){return withDatabase(db=>{const template=db.prepare("SELECT * FROM app_document_templates WHERE id=? AND is_active=1").get(templateId) as Row|undefined;if(!template) throw new Error("문서 템플릿을 찾을 수 없습니다.");const worker=db.prepare("SELECT * FROM app_workers WHERE id=?").get(workerId) as Row|undefined;if(!worker) throw new Error("인력을 찾을 수 없습니다.");const assignment=db.prepare(`SELECT a.*,s.name site_name,j.name job_name FROM app_assignments a JOIN app_sites s ON s.id=a.site_id JOIN app_jobs j ON j.id=a.job_id WHERE a.worker_id=? ORDER BY CASE a.status WHEN '활성' THEN 0 WHEN '예정' THEN 1 ELSE 2 END,a.started_at DESC LIMIT 1`).get(workerId) as Row|undefined;const contract=db.prepare("SELECT * FROM app_contracts WHERE worker_id=? ORDER BY sequence_no DESC,id DESC LIMIT 1").get(workerId) as Row|undefined;const values:Record<string,string>={worker_name:escapeHtml(worker.name),employee_no:escapeHtml(worker.employee_no||"미등록"),joined_at:escapeHtml(worker.joined_at||"미등록"),site_name:escapeHtml(assignment?.site_name||"미배치"),job_name:escapeHtml(assignment?.job_name||"미배치"),contract_period:escapeHtml(contract?`${v(contract.started_at)} ~ ${v(contract.ended_at)}`:"미등록")};let html=v(template.body_html);for(const [key,value] of Object.entries(values)) html=html.replaceAll(`{{${key}}}`,value);const title=`${v(template.name)} - ${v(worker.name)}`;const r=db.prepare("INSERT INTO app_generated_documents(template_id,worker_id,title,rendered_html,template_version,generated_by_user_id) VALUES(?,?,?,?,?,?)").run(templateId,workerId,title,html,Number(template.version_no||1),userId);return Number(r.lastInsertRowid);});}
