import "server-only";
import { withDatabase } from "@/lib/database";

type Row=Record<string,unknown>;
const all=(sql:string,...params:unknown[])=>withDatabase(db=>db.prepare(sql).all(...params) as Row[]);
const one=(sql:string,...params:unknown[])=>withDatabase(db=>db.prepare(sql).get(...params) as Row|undefined);
const n=(v:unknown)=>Number(v??0);

export function listExitSettlements(){return all(`SELECT e.*,w.name worker_name,w.employee_no,s.name site_name,j.name job_name FROM app_exit_settlements e JOIN app_workers w ON w.id=e.worker_id LEFT JOIN app_assignments a ON a.id=e.assignment_id LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id ORDER BY CASE e.status WHEN '예정' THEN 0 WHEN '검토' THEN 1 ELSE 2 END,e.exit_date DESC`);}
export function getExitSettlement(id:number){return one(`SELECT e.*,w.name worker_name,w.employee_no,w.status worker_status,s.name site_name,j.name job_name FROM app_exit_settlements e JOIN app_workers w ON w.id=e.worker_id LEFT JOIN app_assignments a ON a.id=e.assignment_id LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id WHERE e.id=?`,id);}
export function exitOptions(){return all(`SELECT w.id,w.name,w.employee_no,a.id assignment_id,s.name site_name,j.name job_name FROM app_workers w LEFT JOIN app_assignments a ON a.worker_id=w.id AND a.status='활성' LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id WHERE w.status<>'퇴사' ORDER BY w.name`);}

export function createExitSettlement(values:Record<string,unknown>){return withDatabase(db=>{const workerId=n(values.worker_id);const exitDate=String(values.exit_date||"");if(!workerId||!exitDate)throw new Error("근로자와 퇴사일은 필수입니다.");const assignment=db.prepare("SELECT id FROM app_assignments WHERE worker_id=? AND status='활성' ORDER BY started_at DESC,id DESC LIMIT 1").get(workerId) as Row|undefined;const month=exitDate.slice(0,7);const payroll=db.prepare(`SELECT i.id FROM app_payroll_items i JOIN app_payroll_runs r ON r.id=i.payroll_run_id WHERE i.worker_id=? AND r.payroll_month=? LIMIT 1`).get(workerId,month) as Row|undefined;const amount=n(values.unused_leave_pay)+n(values.severance_pay)+n(values.other_payment)-n(values.other_deduction);const r=db.prepare(`INSERT INTO app_exit_settlements(worker_id,assignment_id,payroll_item_id,planned_exit_date,last_work_date,exit_date,exit_reason,remaining_leave_days,unused_leave_pay,severance_pay,other_payment,other_deduction,final_settlement_amount,privacy_delete_date,status,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(workerId,assignment?.id??null,payroll?.id??null,values.planned_exit_date||null,values.last_work_date||null,exitDate,values.exit_reason||null,n(values.remaining_leave_days),n(values.unused_leave_pay),n(values.severance_pay),n(values.other_payment),n(values.other_deduction),amount,values.privacy_delete_date||null,"예정",values.note||null);db.prepare("INSERT INTO app_audit_logs(action,entity_type,entity_id,summary) VALUES('create','exit_settlement',?,'퇴사정산 생성')").run(r.lastInsertRowid);return Number(r.lastInsertRowid);});}

export function updateExitSettlement(id:number,values:Record<string,unknown>){withDatabase(db=>{const amount=n(values.unused_leave_pay)+n(values.severance_pay)+n(values.other_payment)-n(values.other_deduction);db.prepare(`UPDATE app_exit_settlements SET last_work_date=?,exit_reason=?,remaining_leave_days=?,unused_leave_pay=?,severance_pay=?,other_payment=?,other_deduction=?,final_settlement_amount=?,contract_closed=?,property_returned=?,handover_completed=?,documents_completed=?,privacy_delete_date=?,status=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(values.last_work_date||null,values.exit_reason||null,n(values.remaining_leave_days),n(values.unused_leave_pay),n(values.severance_pay),n(values.other_payment),n(values.other_deduction),amount,n(values.contract_closed),n(values.property_returned),n(values.handover_completed),n(values.documents_completed),values.privacy_delete_date||null,values.status||"예정",values.note||null,id);if(values.status==="완료"){const e=db.prepare("SELECT worker_id,exit_date,assignment_id FROM app_exit_settlements WHERE id=?").get(id) as Row;db.prepare("UPDATE app_workers SET status='퇴사',left_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(e.exit_date,e.worker_id);if(e.assignment_id)db.prepare("UPDATE app_assignments SET status='종료',ended_at=COALESCE(ended_at,?),updated_at=CURRENT_TIMESTAMP WHERE id=?").run(e.exit_date,e.assignment_id);db.prepare("UPDATE app_contracts SET status='종료',updated_at=CURRENT_TIMESTAMP WHERE worker_id=? AND status IN ('유효','예정')").run(e.worker_id);}db.prepare("INSERT INTO app_audit_logs(action,entity_type,entity_id,summary) VALUES('update','exit_settlement',?,'퇴사정산 수정')").run(id);});}
