import "server-only";
import { withDatabase } from "@/lib/database";

type Row=Record<string,unknown>;
type PayrollAnomaly={worker_id:number;name:string;gross_pay:number;previous_gross:number;diff:number;rate:number};
type BillingAnomaly={worker_id:number;name:string;total_amount:number;previous_total:number;diff:number;rate:number};
const n=(v:unknown)=>Number(v??0);
export function currentMonth(){return new Date().toISOString().slice(0,7);}
export function monthStatus(month:string){return withDatabase(db=>db.prepare("SELECT * FROM app_attendance_months WHERE month=?").get(month) as Row|undefined);}
export function attendanceMonthSummary(month:string){return withDatabase(db=>{
  db.prepare("INSERT OR IGNORE INTO app_attendance_months(month) VALUES(?)").run(month);
  const workers=db.prepare(`SELECT w.id,w.employee_no,w.name,s.name site_name,j.name job_name,
    COALESCE(SUM(CASE WHEN e.event_type='연장' THEN e.minutes ELSE 0 END),0) overtime_minutes,
    COALESCE(SUM(CASE WHEN e.event_type='휴일' THEN e.minutes ELSE 0 END),0) holiday_minutes,
    COALESCE(SUM(CASE WHEN e.event_type='야간' THEN e.minutes ELSE 0 END),0) night_minutes,
    COALESCE(SUM(CASE WHEN e.event_type='결근' THEN e.days ELSE 0 END),0) absence_days,
    COALESCE(SUM(CASE WHEN e.event_type='무급' THEN e.days ELSE 0 END),0) unpaid_days,
    COALESCE(r.reviewed,0) reviewed
    FROM app_workers w
    JOIN app_assignments a ON a.worker_id=w.id AND date(a.started_at)<=date(?||'-01','+1 month','-1 day') AND (a.ended_at IS NULL OR date(a.ended_at)>=date(?||'-01'))
    LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id
    LEFT JOIN app_attendance_events e ON e.worker_id=w.id AND substr(e.work_date,1,7)=?
    LEFT JOIN app_attendance_month_reviews r ON r.worker_id=w.id AND r.month=?
    WHERE w.status IN ('재직','입사예정','퇴사예정')
    GROUP BY w.id ORDER BY s.name,w.name`).all(month,month,month,month) as Row[];
  const status=db.prepare("SELECT * FROM app_attendance_months WHERE month=?").get(month) as Row;
  return {status,workers,reviewedCount:workers.filter(w=>n(w.reviewed)===1).length};
});}
export function setAttendanceReviewed(month:string,workerId:number,reviewed:boolean,userId:number){withDatabase(db=>db.prepare(`INSERT INTO app_attendance_month_reviews(month,worker_id,reviewed,reviewed_by_user_id,reviewed_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP)
 ON CONFLICT(month,worker_id) DO UPDATE SET reviewed=excluded.reviewed,reviewed_by_user_id=excluded.reviewed_by_user_id,reviewed_at=CURRENT_TIMESTAMP`).run(month,workerId,reviewed?1:0,userId));}
export function confirmAttendanceMonth(month:string,userId:number){withDatabase(db=>{const active=db.prepare(`SELECT COUNT(DISTINCT w.id) count FROM app_workers w JOIN app_assignments a ON a.worker_id=w.id WHERE w.status IN ('재직','입사예정','퇴사예정') AND date(a.started_at)<=date(?||'-01','+1 month','-1 day') AND (a.ended_at IS NULL OR date(a.ended_at)>=date(?||'-01'))`).get(month,month) as Row;const reviewed=db.prepare("SELECT COUNT(*) count FROM app_attendance_month_reviews WHERE month=? AND reviewed=1").get(month) as Row;if(n(active.count)!==n(reviewed.count))throw new Error("모든 대상자의 근태 확인을 완료해야 월 확정할 수 있습니다.");db.prepare(`INSERT INTO app_attendance_months(month,status,confirmed_by_user_id,confirmed_at,updated_at) VALUES(?,'확정',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(month) DO UPDATE SET status='확정',confirmed_by_user_id=excluded.confirmed_by_user_id,confirmed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP`).run(month,userId);});}
export function reopenAttendanceMonth(month:string,userId:number){withDatabase(db=>{const payroll=db.prepare("SELECT status FROM app_payroll_runs WHERE payroll_month=?").get(month) as Row|undefined;if(payroll&&['승인','마감'].includes(String(payroll.status)))throw new Error("승인 또는 마감된 급여가 있어 근태 확정을 해제할 수 없습니다.");db.prepare("UPDATE app_attendance_months SET status='작성중',reopened_by_user_id=?,reopened_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE month=?").run(userId,month);});}
function previousMonth(month:string){const [y,m]=month.split('-').map(Number);return new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7);}
export const anomalyThresholds={payrollRate:0.15,payrollAmount:300000,billingRate:0.15,billingAmount:500000};
export function payrollAnomalies(month:string):PayrollAnomaly[]{return withDatabase(db=>{const prev=previousMonth(month);const current=db.prepare(`SELECT i.worker_id,w.name,i.gross_pay FROM app_payroll_items i JOIN app_payroll_runs r ON r.id=i.payroll_run_id JOIN app_workers w ON w.id=i.worker_id WHERE r.payroll_month=?`).all(month) as Row[];const previous=db.prepare(`SELECT i.worker_id,i.gross_pay FROM app_payroll_items i JOIN app_payroll_runs r ON r.id=i.payroll_run_id WHERE r.payroll_month=?`).all(prev) as Row[];const map=new Map(previous.map(r=>[n(r.worker_id),n(r.gross_pay)]));return current.map(r=>{const old=map.get(n(r.worker_id))??0;const now=n(r.gross_pay);const diff=now-old;const rate=old?diff/old:0;return {worker_id:n(r.worker_id),name:String(r.name??""),gross_pay:now,previous_gross:old,diff,rate};}).filter(r=>Math.abs(r.diff)>=anomalyThresholds.payrollAmount||Math.abs(r.rate)>=anomalyThresholds.payrollRate);});}
export function billingAnomalies(month:string):BillingAnomaly[]{return withDatabase(db=>{const prev=previousMonth(month);const current=db.prepare(`SELECT i.worker_id,w.name,i.total_amount FROM app_billing_items i JOIN app_billing_runs r ON r.id=i.billing_run_id JOIN app_workers w ON w.id=i.worker_id WHERE r.billing_month=?`).all(month) as Row[];const previous=db.prepare(`SELECT i.worker_id,i.total_amount FROM app_billing_items i JOIN app_billing_runs r ON r.id=i.billing_run_id WHERE r.billing_month=?`).all(prev) as Row[];const map=new Map(previous.map(r=>[n(r.worker_id),n(r.total_amount)]));return current.map(r=>{const old=map.get(n(r.worker_id))??0;const now=n(r.total_amount);const diff=now-old;const rate=old?diff/old:0;return {worker_id:n(r.worker_id),name:String(r.name??""),total_amount:now,previous_total:old,diff,rate};}).filter(r=>Math.abs(r.diff)>=anomalyThresholds.billingAmount||Math.abs(r.rate)>=anomalyThresholds.billingRate);});}
export function dashboardInbox(){const month=currentMonth();return withDatabase(db=>{const one=(sql:string,...p:unknown[])=>db.prepare(sql).get(...p) as Row;const attendance=db.prepare("SELECT status FROM app_attendance_months WHERE month=?").get(month) as Row|undefined;const payroll=db.prepare("SELECT status,(SELECT COUNT(*) FROM app_payroll_items i WHERE i.payroll_run_id=r.id AND i.review_status='확인필요') review_count FROM app_payroll_runs r WHERE payroll_month=?").get(month) as Row|undefined;const billing=db.prepare("SELECT status,(SELECT COUNT(*) FROM app_billing_items i WHERE i.billing_run_id=r.id AND i.review_status='확인필요') review_count FROM app_billing_runs r WHERE billing_month=?").get(month) as Row|undefined;return {month,attendanceStatus:String(attendance?.status??'미확정'),payrollStatus:String(payroll?.status??'미생성'),billingStatus:String(billing?.status??'미생성'),payrollReview:n(payroll?.review_count),billingReview:n(billing?.review_count),contract7:n(one("SELECT COUNT(*) count FROM app_contracts WHERE status='유효' AND date(ended_at) BETWEEN date('now') AND date('now','+7 day')").count),contract30:n(one("SELECT COUNT(*) count FROM app_contracts WHERE status='유효' AND date(ended_at) BETWEEN date('now') AND date('now','+30 day')").count),upcomingJoin:n(one("SELECT COUNT(*) count FROM app_workers WHERE status='입사예정' AND date(joined_at) BETWEEN date('now') AND date('now','+7 day')").count),upcomingExit:n(one("SELECT COUNT(*) count FROM app_exit_settlements WHERE status!='완료' AND date(exit_date) BETWEEN date('now') AND date('now','+7 day')").count),substituteOpen:n(one("SELECT COUNT(*) count FROM app_substitute_requests WHERE status='요청' AND date(work_date)<=date('now','+7 day')").count)};});}
