import Link from "next/link";
import { notFound } from "next/navigation";
import { savePayrollItem, setPayrollStatus } from "@/app/payroll/actions";
import { getPayrollRun, won } from "@/lib/payroll";

export const dynamic = "force-dynamic";
const v=(x:unknown)=>String(x??"");
const num=(x:unknown)=>Number(x??0);

export default async function PayrollRunPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; const data=getPayrollRun(Number(id)); if(!data) notFound();
  const {run,items}=data; const locked=v(run.status)==="마감";
  const total=items.reduce((sum,item)=>sum+num(item.gross_pay),0);
  const reviewCount=items.filter(item=>v(item.review_status)==="확인필요").length;
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/payroll" className="text-sm font-semibold text-teal-700">← 급여 회차</Link><h1 className="mt-2 text-3xl font-bold text-slate-950">{v(run.payroll_month)} 급여</h1><p className="mt-1 text-sm text-slate-500">기준일수 {v(run.standard_days)}일 · {items.length}명 · 지급총액 {won(total)}</p></div><span className={`rounded-full px-3 py-1.5 text-sm font-bold ${locked?"bg-slate-100 text-slate-700":"bg-teal-50 text-teal-800"}`}>{v(run.status)}</span></header>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">급여 대상</p><p className="mt-2 text-2xl font-black">{items.length}명</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">확인 필요</p><p className={`mt-2 text-2xl font-black ${reviewCount?"text-amber-700":"text-emerald-700"}`}>{reviewCount}명</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">지급 총액</p><p className="mt-2 text-2xl font-black">{won(total)}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">상태</p><p className="mt-2 text-2xl font-black">{v(run.status)}</p></div></section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">검토·마감</h2><p className="mt-1 text-xs text-slate-500">확인필요가 0명이어야 승인·마감할 수 있습니다. 마감 후에는 수정할 수 없습니다.</p></div><div className="flex flex-wrap gap-2">{["작성중","검토","승인","마감"].map(status=><form action={setPayrollStatus} key={status}><input type="hidden" name="id" value={v(run.id)} /><input type="hidden" name="status" value={status} /><button disabled={locked || (status!=="작성중"&&status!=="검토"&&reviewCount>0)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold disabled:cursor-not-allowed disabled:opacity-40">{status}</button></form>)}</div></div></section>

    <section className="space-y-3">{items.map(item=><details key={v(item.id)} className={`rounded-2xl border bg-white shadow-sm ${v(item.review_status)==="확인필요"?"border-amber-300":"border-slate-200"}`}><summary className="flex cursor-pointer list-none flex-wrap items-center gap-3 px-5 py-4"><div className="min-w-[160px] flex-1"><p className="font-bold text-slate-950">{v(item.worker_name)}</p><p className="mt-1 text-xs text-slate-500">{v(item.site_name)} · {v(item.job_name)} · {v(item.employee_no)||"사번 없음"}</p></div><div className="text-right"><p className="font-black text-slate-950">{won(item.gross_pay)}</p><p className={`mt-1 text-xs font-bold ${v(item.review_status)==="확인필요"?"text-amber-700":"text-emerald-700"}`}>{v(item.review_status)}</p></div></summary><div className="border-t border-slate-100 p-5">
      {v(item.review_status)==="확인필요"?<div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">급여기준 미연결 또는 입·퇴사 월일 수 있습니다. 근무일수와 금액을 확인해 저장하세요.</div>:null}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6 text-sm"><div><p className="text-xs text-slate-400">기본급 기준</p><p className="mt-1 font-bold">{won(item.base_salary)}</p></div><div><p className="text-xs text-slate-400">식대 기준</p><p className="mt-1 font-bold">{won(item.meal_allowance)}</p></div><div><p className="text-xs text-slate-400">통상시급</p><p className="mt-1 font-bold">{won(item.ordinary_hourly)}</p></div><div><p className="text-xs text-slate-400">기본급 일할</p><p className="mt-1 font-bold">{won(item.base_current)}</p></div><div><p className="text-xs text-slate-400">식대 일할</p><p className="mt-1 font-bold">{won(item.meal_current)}</p></div><div><p className="text-xs text-slate-400">결근·무급·휴직</p><p className="mt-1 font-bold">{v(item.absence_days)}일</p></div></div>
      <form action={savePayrollItem} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><input type="hidden" name="id" value={v(item.id)} />
        <label className="text-xs font-semibold text-slate-500">근무일수<input name="worked_days" type="number" step="0.5" min="0" defaultValue={v(item.worked_days)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm disabled:bg-slate-50" /></label>
        <label className="text-xs font-semibold text-slate-500">연장시간<input name="overtime_hours" type="number" step="0.25" min="0" defaultValue={v(item.overtime_hours)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">휴일시간<input name="holiday_hours" type="number" step="0.25" min="0" defaultValue={v(item.holiday_hours)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">야간시간<input name="night_hours" type="number" step="0.25" min="0" defaultValue={v(item.night_hours)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">연차수당<input name="leave_pay" type="number" step="1" defaultValue={v(item.leave_pay)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">인센티브<input name="incentive" type="number" step="1" defaultValue={v(item.incentive)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">소급지급<input name="retroactive_pay" type="number" step="1" defaultValue={v(item.retroactive_pay)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">기타지급<input name="other_pay" type="number" step="1" defaultValue={v(item.other_pay)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">기타공제<input name="other_deduction" type="number" step="1" defaultValue={v(item.other_deduction)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500">수동조정<input name="manual_adjustment" type="number" step="1" defaultValue={v(item.manual_adjustment)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label>
        <label className="text-xs font-semibold text-slate-500 sm:col-span-2 lg:col-span-2">조정사유<input name="manual_reason" defaultValue={v(item.manual_reason)} disabled={locked} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="수동조정 시 필수" /></label>
        <div className="sm:col-span-2 lg:col-span-4 xl:col-span-6 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div className="text-sm"><span className="text-slate-500">연장 {won(item.overtime_pay)} · 휴일 {won(item.holiday_pay)} · 야간 {won(item.night_pay)}</span><p className="mt-1 text-lg font-black">지급총액 {won(item.gross_pay)}</p></div>{!locked?<button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">재계산·저장</button>:<span className="text-xs font-bold text-slate-500">마감됨</span>}</div>
      </form>
    </div></details>)}
    {!items.length?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-400">급여 대상자가 없습니다.</div>:null}</section>
  </div>;
}
