import type { Metadata } from "next";
import Link from "next/link";
import { createAssignment, createContract, endAssignment } from "@/app/actions";
import { listAssignments, listContracts, options } from "@/lib/operations";

export const metadata: Metadata = { title: "배치·계약" };
export const dynamic = "force-dynamic";
const v=(x:unknown)=>String(x??"");

export default function Page(){
  const assignments=listAssignments(),contracts=listContracts(),opts=options();
  return <div className="space-y-6">
    <header><p className="text-sm font-semibold text-teal-700">인력 운영</p><h1 className="mt-1 text-3xl font-bold text-slate-950">배치·계약</h1><p className="mt-2 text-sm text-slate-500">지점·직무 배치와 계약 연장을 별도 이력으로 관리합니다.</p></header>
    <div className="grid gap-6 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">배치 등록</h2>
        <form action={createAssignment} className="mt-4 grid gap-3 sm:grid-cols-2"><select name="worker_id" required className="h-11 rounded-xl border border-slate-200 px-3 text-sm sm:col-span-2"><option value="">인력 선택 *</option>{opts.workers.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.name)} {r.employee_no?`(${v(r.employee_no)})`:""}</option>)}</select><select name="site_id" required className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">지점 *</option>{opts.sites.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.name)}</option>)}</select><select name="job_id" required className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">직무 *</option>{opts.jobs.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.name)}</option>)}</select><input name="started_at" type="date" required aria-label="배치 시작일" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><select name="work_type" defaultValue="주중" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option>주중</option><option>주말</option><option>스케줄</option><option>야간</option><option>단기</option></select><select name="pay_rule_id" className="h-11 rounded-xl border border-slate-200 px-3 text-sm sm:col-span-2"><option value="">급여기준 선택(선택)</option>{opts.payRules.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.job_name)} · {v(r.effective_from)}</option>)}</select><button className="rounded-xl bg-teal-700 px-5 py-2.5 text-sm font-bold text-white sm:col-span-2">배치 등록</button></form>
      </section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">계약 등록·연장</h2>
        <form action={createContract} className="mt-4 grid gap-3 sm:grid-cols-2"><select name="worker_id" required className="h-11 rounded-xl border border-slate-200 px-3 text-sm sm:col-span-2"><option value="">인력 선택 *</option>{opts.workers.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.name)}</option>)}</select><select name="contract_type" defaultValue="최초" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option>최초</option><option>연장</option><option>변경</option><option>종료</option></select><select name="status" defaultValue="유효" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option>예정</option><option>유효</option><option>만료</option><option>종료</option></select><input name="started_at" type="date" required aria-label="계약 시작일" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="ended_at" type="date" required aria-label="계약 종료일" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="note" placeholder="연장·변경 사유" className="h-11 rounded-xl border border-slate-200 px-3 text-sm sm:col-span-2"/><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white sm:col-span-2">계약 저장</button></form>
      </section>
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">현재 배치</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">인력</th><th>지점</th><th>직무</th><th>근무형태</th><th>시작일</th><th>계약 종료</th><th>상태</th><th></th></tr></thead><tbody>{assignments.map(a=><tr key={v(a.id)} className="border-b border-slate-100"><td className="px-4 py-3"><Link href={`/workers/${v(a.worker_id)}`} className="font-bold text-slate-950 hover:text-teal-700">{v(a.worker_name)}</Link></td><td>{v(a.site_name)}</td><td>{v(a.job_name)}</td><td>{v(a.work_type)}</td><td>{v(a.started_at)}</td><td>{v(a.contract_ended)||"-"}</td><td>{v(a.status)}</td><td>{v(a.status)==="활성"?<form action={endAssignment}><input type="hidden" name="id" value={v(a.id)}/><button className="text-xs font-bold text-rose-600">배치 종료</button></form>:null}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">계약 이력</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">인력</th><th>회차</th><th>구분</th><th>지점·직무</th><th>기간</th><th>상태</th></tr></thead><tbody>{contracts.map(c=><tr key={v(c.id)} className="border-b border-slate-100"><td className="px-4 py-3 font-bold">{v(c.worker_name)}</td><td>{v(c.sequence_no)}차</td><td>{v(c.contract_type)}</td><td>{v(c.site_name)} {v(c.job_name)}</td><td>{v(c.started_at)} ~ {v(c.ended_at)}</td><td>{v(c.status)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
