"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { auditAs, requireOwner, requireUser } from "@/lib/auth";
import { withDatabase } from "@/lib/database";
import { changeBillingStatus, createBillingRule, generateBillingRun, updateBillingItem } from "@/lib/billing";
import { reopenBillingRun } from "@/lib/billing-admin";
const t=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const n=(f:FormData,k:string)=>Number(t(f,k)||0);
type BillingStatus="작성중"|"검토"|"승인"|"마감";
const allowed:Record<BillingStatus,BillingStatus[]>={작성중:["검토"],검토:["작성중","승인"],승인:["마감"],마감:[]};
function getRunStatus(id:number){return withDatabase(db=>{const row=db.prepare("SELECT status FROM app_billing_runs WHERE id=?").get(id) as {status?:BillingStatus}|undefined;if(!row?.status)throw new Error("청구회차를 찾을 수 없습니다.");return row.status;});}
function getRunStatusByItem(id:number){return withDatabase(db=>{const row=db.prepare(`SELECT r.status FROM app_billing_items i JOIN app_billing_runs r ON r.id=i.billing_run_id WHERE i.id=?`).get(id) as {status?:BillingStatus}|undefined;if(!row?.status)throw new Error("청구 항목을 찾을 수 없습니다.");return row.status;});}
export async function saveBillingRule(form:FormData){const user=await requireOwner();createBillingRule({name:t(form,"name"),effective_from:t(form,"effective_from"),effective_to:t(form,"effective_to"),pension_rate:n(form,"pension_rate"),health_rate:n(form,"health_rate"),long_term_care_rate:n(form,"long_term_care_rate"),employment_rate:n(form,"employment_rate"),industrial_accident_rate:n(form,"industrial_accident_rate"),wage_claim_rate:n(form,"wage_claim_rate"),asbestos_relief_rate:n(form,"asbestos_relief_rate"),disability_rate:n(form,"disability_rate"),local_business_tax_rate:n(form,"local_business_tax_rate"),welfare_rate:n(form,"welfare_rate"),accident_reserve_rate:n(form,"accident_reserve_rate"),management_fee_rate:n(form,"management_fee_rate"),profit_rate:n(form,"profit_rate"),vat_rate:n(form,"vat_rate"),review_status:t(form,"review_status"),note:t(form,"note")});auditAs(user,"create","billing_rule",null,`청구 기준 ${t(form,"name")} 등록`);revalidatePath("/billing");}
export async function createBillingRun(form:FormData){const user=await requireUser();const id=generateBillingRun(t(form,"billing_month"),n(form,"billing_rule_id"),t(form,"note"));auditAs(user,"create","billing_run",id,`${t(form,"billing_month")} 청구회차 생성`);revalidatePath("/billing");redirect(`/billing/${id}`);}
export async function saveBillingItem(form:FormData){const user=await requireUser();const id=n(form,"id");const status=getRunStatusByItem(id);if(status==="승인"||status==="마감")throw new Error("승인 또는 마감된 청구는 수정할 수 없습니다. 관리자가 검토 상태로 되돌린 뒤 수정하세요.");const runId=updateBillingItem(id,n(form,"one_time_cost"),n(form,"manual_adjustment"),t(form,"manual_reason"));auditAs(user,"update","billing_item",id,"청구 항목 수정");revalidatePath(`/billing/${runId}`);revalidatePath("/billing");}
export async function setBillingStatus(form:FormData){const id=n(form,"id");const status=t(form,"status") as BillingStatus;const current=getRunStatus(id);if(current===status)return;if(!allowed[current]?.includes(status))throw new Error(`청구 상태는 ${current}에서 ${status}(으)로 바로 변경할 수 없습니다.`);const user=(status==="승인"||status==="마감")?await requireOwner():await requireUser();changeBillingStatus(id,status);auditAs(user,"status","billing_run",id,`청구 상태 ${current} → ${status}`);revalidatePath(`/billing/${id}`);revalidatePath("/billing");revalidatePath("/");}
export async function reopenBilling(form:FormData){const user=await requireOwner();const id=n(form,"id");const current=getRunStatus(id);if(current!=="승인"&&current!=="마감")throw new Error("승인 또는 마감 상태만 검토로 되돌릴 수 있습니다.");reopenBillingRun(id);auditAs(user,"unlock","billing_run",id,`청구 ${current} → 검토`);revalidatePath(`/billing/${id}`);revalidatePath("/billing");revalidatePath("/");}
