"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { auditAs, requireOwner, requireUser } from "@/lib/auth";
import { changeBillingStatus, createBillingRule, generateBillingRun, updateBillingItem } from "@/lib/billing";
import { reopenBillingRun } from "@/lib/billing-admin";
const t=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const n=(f:FormData,k:string)=>Number(t(f,k)||0);
export async function saveBillingRule(form:FormData){const user=await requireOwner();createBillingRule({name:t(form,"name"),effective_from:t(form,"effective_from"),effective_to:t(form,"effective_to"),pension_rate:n(form,"pension_rate"),health_rate:n(form,"health_rate"),long_term_care_rate:n(form,"long_term_care_rate"),employment_rate:n(form,"employment_rate"),industrial_accident_rate:n(form,"industrial_accident_rate"),wage_claim_rate:n(form,"wage_claim_rate"),asbestos_relief_rate:n(form,"asbestos_relief_rate"),disability_rate:n(form,"disability_rate"),local_business_tax_rate:n(form,"local_business_tax_rate"),welfare_rate:n(form,"welfare_rate"),accident_reserve_rate:n(form,"accident_reserve_rate"),management_fee_rate:n(form,"management_fee_rate"),profit_rate:n(form,"profit_rate"),vat_rate:n(form,"vat_rate"),review_status:t(form,"review_status"),note:t(form,"note")});auditAs(user,"create","billing_rule",null,`청구 기준 ${t(form,"name")} 등록`);revalidatePath("/billing");}
export async function createBillingRun(form:FormData){const user=await requireUser();const id=generateBillingRun(t(form,"billing_month"),n(form,"billing_rule_id"),t(form,"note"));auditAs(user,"create","billing_run",id,`${t(form,"billing_month")} 청구회차 생성`);revalidatePath("/billing");redirect(`/billing/${id}`);}
export async function saveBillingItem(form:FormData){const user=await requireUser();const id=n(form,"id");const runId=updateBillingItem(id,n(form,"one_time_cost"),n(form,"manual_adjustment"),t(form,"manual_reason"));auditAs(user,"update","billing_item",id,"청구 항목 수정");revalidatePath(`/billing/${runId}`);revalidatePath("/billing");}
export async function setBillingStatus(form:FormData){const id=n(form,"id");const status=t(form,"status") as "작성중"|"검토"|"승인"|"마감";const user=(status==="승인"||status==="마감")?await requireOwner():await requireUser();changeBillingStatus(id,status);auditAs(user,"status","billing_run",id,`청구 상태 ${status}`);revalidatePath(`/billing/${id}`);revalidatePath("/billing");revalidatePath("/");}
export async function reopenBilling(form:FormData){const user=await requireOwner();const id=n(form,"id");reopenBillingRun(id);auditAs(user,"unlock","billing_run",id,"청구 마감 해제");revalidatePath(`/billing/${id}`);revalidatePath("/billing");revalidatePath("/");}
