import Link from "next/link";
import type { Metadata } from "next";
import { createSubstitutePerson, createSubstituteRequest, completeSubstituteRequest, cancelSubstituteRequest } from "@/app/phase2-actions";
import { phase2Options, substituteOverview } from "@/lib/phase2";

export const metadata: Metadata = { title: "대체근무" };
export const dynamic = "force-dynamic";
const input="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-500";
const card="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";

export default function Page(){
  const data=substituteOverview(), options=phase2Options();
  const open=data.requests.filter(r=>["요청","섭외중"].includes(String(r.status))).length;
  return <div className="space-y-6">
    <header><p className="text-sm font-semibold text-teal-700">요청 → 후보 → 배정 → 완료</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">대체근무</h1><p className="mt-2 text-sm text-slate-500">대체근무 이력을 쌓을수록 같은 지점·직무 경험자를 우선 추천합니다.</p></header>
    <section className="grid gap-4 md:grid-cols-3"><Stat label="활동 대체인력" value={`${data.people.filter(r=>String(r.status)==="활동").length}명`}/><Stat label="미배정 요청" value={`${open}건`}/><Stat label="전체 요청" value={`${data.requests.length}건`}/></section>
    <div className="grid gap-6 xl:grid-cols-2">
      <section className={card}><h2 className="text-lg font-bold">대체근무 요청</h2><form action={createSubstituteRequest} className="mt-4 grid gap-3 sm:grid-cols-2"><select className={input} name="site_id" required><option value="">지점 선택</option>{options.sites.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.name)}</option>)}</select><select className={input} name="job_id" required><option value="">직무 선택</option>{options.jobs.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.name)}</option>)}</select><input className={input} type="date" name="work_date" required/><input className={input} type="number" name="hours" step="0.5" min="0" placeholder="근무시간"/><input className={input} type="time" name="started_at"/><input className={input} type="time" name="ended_at"/><input className={`${input} sm:col-span-2`} name="reason" placeholder="대체 사유"/><input className={`${input} sm:col-span-2`} name="note" placeholder="메모"/><button className="h-10 rounded-lg bg-teal-700 px-4 text-sm font-bold text-white sm:col-span-2">요청 생성 후 후보 보기</button></form></section>
      <section className={card}><h2 className="text-lg font-bold">대체인력 등록</h2><form action={createSubstitutePerson} className="mt-4 grid gap-3 sm:grid-cols-2"><input className={input} name="name" placeholder="성명" required/><input className={input} name="phone" placeholder="연락처"/><input className={input} name="experience_type" placeholder="경험 유형 (예: 서비스센터)"/><select className={input} name="status"><option>활동</option><option>보류</option><option>종료</option></select><input className={`${input} sm:col-span-2`} name="note" placeholder="특이사항"/><button className="h-10 rounded-lg bg-slate-900 px-4 text-sm font-bold text-white sm:col-span-2">대체인력 저장</button></form></section>
    </div>
    <section className={card}><h2 className="text-lg font-bold">대체근무 요청 현황</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{["날짜","지점","직무","시간","사유","배정자","상태","처리"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{data.requests.map(r=><tr key={String(r.id)} className="border-b border-slate-100"><td className="px-3 py-3">{String(r.work_date)}</td><td className="px-3 py-3 font-semibold">{String(r.site_name)}</td><td className="px-3 py-3">{String(r.job_name)}</td><td className="px-3 py-3">{r.hours?`${String(r.hours)}h`:"-"}</td><td className="px-3 py-3 text-slate-500">{String(r.reason??"-")}</td><td className="px-3 py-3">{String(r.substitute_name??"-")}</td><td className="px-3 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{String(r.status)}</span></td><td className="px-3 py-3"><div className="flex gap-2"><Link href={`/substitutes/${String(r.id)}`} className="text-xs font-bold text-teal-700">후보</Link>{String(r.status)==="배정"&&<form action={completeSubstituteRequest}><input type="hidden" name="request_id" value={String(r.id)}/><button className="text-xs font-bold text-blue-700">완료</button></form>}{!["완료","취소"].includes(String(r.status))&&<form action={cancelSubstituteRequest}><input type="hidden" name="request_id" value={String(r.id)}/><button className="text-xs font-bold text-rose-600">취소</button></form>}</div></td></tr>)}</tbody></table></div></section>
    <section className={card}><h2 className="text-lg font-bold">대체인력 DB</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{["성명","연락처","경험유형","총 근무","경험 지점","경험 직무","최근 근무","상태"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{data.people.map(r=><tr key={String(r.id)} className="border-b border-slate-100"><td className="px-3 py-3 font-semibold">{String(r.name)}</td><td className="px-3 py-3">{String(r.phone??"-")}</td><td className="px-3 py-3">{String(r.experience_type??"-")}</td><td className="px-3 py-3 font-bold text-teal-700">{String(r.total_count??0)}회</td><td className="max-w-[220px] truncate px-3 py-3">{String(r.site_names??"-")}</td><td className="max-w-[220px] truncate px-3 py-3">{String(r.job_names??"-")}</td><td className="px-3 py-3">{String(r.recent_work_date??"-")}</td><td className="px-3 py-3">{String(r.status)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
function Stat({label,value}:{label:string;value:string}){return <div className={card}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>}
