import Link from "next/link";
import { notFound } from "next/navigation";
import { createAssignment, createContract, updateWorker } from "@/app/actions";
import { getWorker, options } from "@/lib/operations";
import { getWorkerHub } from "@/lib/worker-hub";

export const dynamic="force-dynamic";
const v=(x:unknown)=>String(x??"");
const num=(x:unknown)=>Number(x??0);
const won=(x:unknown)=>`${Math.round(num(x)).toLocaleString("ko-KR")}원`;
const card="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const tabs=[['basic','기본정보'],['assignment','배치'],['contract','계약'],['attendance','근태'],['leave','연차'],['payroll','급여'],['billing','청구'],['documents','문서'],['exit','퇴사'],['history','이력']];

export default async function Page({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const workerId=Number(id);const data=getWorker(workerId);const hub=getWorkerHub(workerId);if(!data||!hub)notFound();
  const {worker,assignments,contracts}=data;const opts=options();const c=hub.current;
  return <div className="space-y-6">
    <header className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/workers" className="text-sm font-semibold text-teal-700">← 인력 목록</Link><div className="mt-2 flex items-center gap-3"><h1 className="text-3xl font-black text-slate-950">{v(worker.name)}</h1><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-800">{v(worker.status)}</span></div><p className="mt-1 text-sm text-slate-500">사번 {v(worker.employee_no)||'미등록'} · 입사 {v(worker.joined_at)||'미등록'}</p></div><div className="grid min-w-[320px] grid-cols-2 gap-2 text-sm sm:grid-cols-4"><Summary label="지점" value={v(c.site_name)||'-'}/><Summary label="직무" value={v(c.job_name)||'-'}/><Summary label="계약종료" value={v(c.contract_ended)||'-'}/><Summary label="연차잔액" value={`${hub.leaveBalance.toFixed(1)}일`}/></div></div><div className="mt-5 flex gap-2 overflow-x-auto border-t border-slate-100 pt-4">{tabs.map(([anchor,label])=><a key={anchor} href={`#${anchor}`} className="shrink-0 rounded-lg bg-slate-50 px-3 py-2 text-xs font-bold text-slate-600 hover:bg-teal-50 hover:text-teal-800">{label}</a>)}</div></header>

    <section id="basic" className={card}><div className="flex items-center justify-between"><div><h2 className="font-bold">기본정보</h2><p className="mt-1 text-xs text-slate-500">인력의 기준정보입니다.</p></div><div className="text-right text-xs text-slate-500"><p>급여기준 {c.pay_rule_id?`${v(c.pay_rule_from)} 적용`:'미연결'}</p><p>{c.base_salary?`기본급 ${won(c.base_salary)}`:''}</p></div></div><form action={updateWorker} className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-4"><input type="hidden" name="id" value={v(worker.id)}/>{[['name','성명'],['employee_no','사번'],['phone','연락처'],['email','이메일']].map(([name,label])=><label key={name} className="text-xs font-semibold text-slate-500">{label}<input name={name} required={name==='name'} defaultValue={v(worker[name])} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label>)}<label className="text-xs font-semibold text-slate-500">생년월일<input name="birth_date" type="date" defaultValue={v(worker.birth_date)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-500">입사일<input name="joined_at" type="date" defaultValue={v(worker.joined_at)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-500">퇴사일<input name="left_at" type="date" defaultValue={v(worker.left_at)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-500">상태<select name="status" defaultValue={v(worker.status)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm">{['입사예정','재직','휴직','퇴사'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-semibold text-slate-500 md:col-span-2">주소<input name="address" defaultValue={v(worker.address)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label><label className="text-xs font-semibold text-slate-500 md:col-span-2">특이사항<input name="note" defaultValue={v(worker.note)} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label><div className="md:col-span-3 xl:col-span-4"><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">기본정보 저장</button></div></form></section>

    <div className="grid gap-6 xl:grid-cols-2"><section id="assignment" className={card}><h2 className="font-bold">배치</h2><form action={createAssignment} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="worker_id" value={v(worker.id)}/><select name="site_id" required className="h-10 rounded-xl border px-3 text-sm"><option value="">지점 선택 *</option>{opts.sites.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.name)}</option>)}</select><select name="job_id" required className="h-10 rounded-xl border px-3 text-sm"><option value="">직무 선택 *</option>{opts.jobs.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.name)}</option>)}</select><input name="started_at" type="date" required className="h-10 rounded-xl border px-3 text-sm"/><select name="work_type" defaultValue="주중" className="h-10 rounded-xl border px-3 text-sm">{['주중','주말','스케줄','야간','단기'].map(x=><option key={x}>{x}</option>)}</select><select name="pay_rule_id" className="h-10 rounded-xl border px-3 text-sm sm:col-span-2"><option value="">급여기준 선택</option>{opts.payRules.map(r=><option key={v(r.id)} value={v(r.id)}>{v(r.job_name)} · {v(r.effective_from)} · {won(r.base_salary)}</option>)}</select><button className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white sm:col-span-2">배치 등록</button></form><div className="mt-5 space-y-2">{assignments.map(a=><div key={v(a.id)} className="rounded-xl border p-3"><div className="flex justify-between"><b>{v(a.site_name)} · {v(a.job_name)}</b><span className="text-xs font-bold text-teal-700">{v(a.status)}</span></div><p className="mt-1 text-xs text-slate-500">{v(a.started_at)} ~ {v(a.ended_at)||'현재'} · {v(a.work_type)}</p></div>)}</div></section>
    <section id="contract" className={card}><h2 className="font-bold">계약</h2><form action={createContract} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="worker_id" value={v(worker.id)}/><select name="assignment_id" className="h-10 rounded-xl border px-3 text-sm sm:col-span-2"><option value="">배치 연결</option>{assignments.map(a=><option key={v(a.id)} value={v(a.id)}>{v(a.site_name)} · {v(a.job_name)} · {v(a.started_at)}</option>)}</select><select name="contract_type" defaultValue={contracts.length?'연장':'최초'} className="h-10 rounded-xl border px-3 text-sm">{['최초','연장','변경','종료'].map(x=><option key={x}>{x}</option>)}</select><select name="status" defaultValue="유효" className="h-10 rounded-xl border px-3 text-sm">{['예정','유효','만료','종료'].map(x=><option key={x}>{x}</option>)}</select><input name="started_at" type="date" required className="h-10 rounded-xl border px-3 text-sm"/><input name="ended_at" type="date" required className="h-10 rounded-xl border px-3 text-sm"/><input name="note" placeholder="계약 메모" className="h-10 rounded-xl border px-3 text-sm sm:col-span-2"/><button className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white sm:col-span-2">계약 등록</button></form><div className="mt-5 space-y-2">{contracts.map(cn=><div key={v(cn.id)} className="rounded-xl border p-3"><div className="flex justify-between"><b>{v(cn.sequence_no)}차 · {v(cn.contract_type)}</b><span className="text-xs font-bold text-teal-700">{v(cn.status)}</span></div><p className="mt-1 text-sm">{v(cn.started_at)} ~ {v(cn.ended_at)}</p></div>)}</div></section></div>

    <div className="grid gap-6 xl:grid-cols-2"><HubTable id="attendance" title="근태" href={`/attendance`} headers={['날짜','유형','시간/일수','비고']} rows={hub.attendance.map(r=>[v(r.work_date),v(r.event_type),num(r.minutes)?`${num(r.minutes)}분`:`${num(r.days)}일`,v(r.note)||'-'])}/><HubTable id="leave" title={`연차 · 잔액 ${hub.leaveBalance.toFixed(1)}일`} href="/attendance" headers={['날짜','유형','일수','비고']} rows={hub.leaveLedger.map(r=>[v(r.event_date),v(r.event_type),`${num(r.leave_days)}일`,v(r.note)||'-'])}/></div>
    <div className="grid gap-6 xl:grid-cols-2"><HubTable id="payroll" title="급여" href="/payroll" headers={['월','상태','지급총액','검토']} rows={hub.payroll.map(r=>[v(r.payroll_month),v(r.run_status),won(r.gross_pay),v(r.review_status)])}/><HubTable id="billing" title="고객사 청구" href="/billing" headers={['월','상태','청구액','검토']} rows={hub.billing.map(r=>[v(r.billing_month),v(r.run_status),won(r.total_amount),v(r.review_status)])}/></div>
    <div className="grid gap-6 xl:grid-cols-2"><HubTable id="documents" title="문서" href={`/documents`} headers={['문서','종류','생성일','생성자']} rows={hub.documents.map(r=>[v(r.title),v(r.document_type),v(r.created_at),v(r.generated_by)||'-'])}/><HubTable id="exit" title="퇴사정산" href="/exits" headers={['퇴사일','상태','연차수당','퇴직금']} rows={hub.exits.map(r=>[v(r.exit_date),v(r.status),won(r.unused_leave_pay),won(r.severance_pay)])}/></div>
    <section id="history" className={card}><div className="flex items-center justify-between"><div><h2 className="font-bold">변경이력</h2><p className="mt-1 text-xs text-slate-500">입사 처리와 인력 변경의 감사 이력입니다.</p></div><Link href="/settings" className="text-xs font-bold text-teal-700">감사로그 전체</Link></div><div className="mt-4 space-y-2">{hub.audits.length?hub.audits.map(r=><div key={v(r.id)} className="flex justify-between gap-4 rounded-xl border p-3 text-sm"><div><b>{v(r.summary)}</b><p className="mt-1 text-xs text-slate-500">{v(r.actor_name)||'시스템'} · {v(r.action)}</p></div><span className="shrink-0 text-xs text-slate-400">{v(r.created_at)}</span></div>):<p className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-400">표시할 변경이력이 없습니다.</p>}</div></section>
  </div>;
}

function Summary({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-semibold text-slate-400">{label}</p><p className="mt-1 truncate text-sm font-bold text-slate-900">{value}</p></div>}
function HubTable({id,title,href,headers,rows}:{id:string;title:string;href:string;headers:string[];rows:string[][]}){return <section id={id} className={card}><div className="flex items-center justify-between"><h2 className="font-bold">{title}</h2><Link href={href} className="text-xs font-bold text-teal-700">전체 관리</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{headers.map(h=><th key={h} className="px-3 py-2.5">{h}</th>)}</tr></thead><tbody>{rows.slice(0,12).map((row,i)=><tr key={i} className="border-t border-slate-100">{row.map((cell,j)=><td key={j} className="px-3 py-3">{cell}</td>)}</tr>)}{!rows.length?<tr><td colSpan={headers.length} className="px-3 py-8 text-center text-slate-400">기록이 없습니다.</td></tr>:null}</tbody></table></div></section>}
