import type { Metadata } from "next";
import { createJob, createPayRule } from "@/app/actions";
import { listJobs, listPayRules, listSites } from "@/lib/operations";

export const metadata: Metadata = { title: "직무·급여기준" };
export const dynamic = "force-dynamic";
const v=(x:unknown)=>String(x??"");
const won=(x:unknown)=>`${Number(x??0).toLocaleString("ko-KR")}원`;

export default function Page(){
  const jobs=listJobs(),rules=listPayRules(),sites=listSites();
  return <div className="space-y-6">
    <header><p className="text-sm font-semibold text-teal-700">기준정보</p><h1 className="mt-1 text-3xl font-bold text-slate-950">직무·급여기준</h1><p className="mt-2 text-sm text-slate-500">직무와 급여조건은 적용기간별 버전으로 관리합니다. 과거 급여기준을 덮어쓰지 않습니다.</p></header>
    <div className="grid gap-6 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">직무 등록</h2>
        <form action={createJob} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="표준 직무명 *" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="display_name" placeholder="표시명" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><select name="work_type" defaultValue="주중" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option>주중</option><option>주말</option><option>스케줄</option><option>야간</option><option>단기</option></select><input name="standard_hours" type="number" step="0.01" placeholder="월 기준시간" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><textarea name="description" placeholder="업무·운영 메모" className="min-h-20 rounded-xl border border-slate-200 p-3 text-sm sm:col-span-2"/><button className="rounded-xl bg-teal-700 px-5 py-2.5 text-sm font-bold text-white sm:col-span-2">직무 등록</button></form>
        <div className="mt-5 space-y-2">{jobs.map(j=><div key={v(j.id)} className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div><p className="font-bold">{v(j.name)}</p><p className="text-xs text-slate-500">{v(j.work_type)} · 현재 {v(j.active_count)}명</p></div><span className="text-xs font-semibold text-teal-700">급여기준 {v(j.rule_count)}개</span></div>)}</div>
      </section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">급여기준 등록</h2><p className="mt-1 text-xs text-slate-500">이번 단계에서는 고정 급여조건과 적용기간을 관리합니다. 월 급여 계산기는 Phase 3에서 연결합니다.</p>
        <form action={createPayRule} className="mt-4 grid gap-3 sm:grid-cols-2"><select name="job_id" required className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">직무 선택 *</option>{jobs.map(j=><option key={v(j.id)} value={v(j.id)}>{v(j.name)}</option>)}</select><select name="site_id" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">전체 지점 공통</option>{sites.map(s=><option key={v(s.id)} value={v(s.id)}>{v(s.name)}</option>)}</select><input name="effective_from" type="date" required aria-label="적용 시작일" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="effective_to" type="date" aria-label="적용 종료일" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="base_salary" type="number" min="0" placeholder="기본급" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="meal_allowance" type="number" min="0" placeholder="식대" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="fixed_overtime_allowance" type="number" min="0" placeholder="고정연장수당" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="fixed_night_allowance" type="number" min="0" placeholder="고정야간수당" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="fixed_holiday_allowance" type="number" min="0" placeholder="고정휴일수당" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="other_allowance" type="number" min="0" placeholder="기타 고정수당" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="monthly_standard_hours" type="number" step="0.01" placeholder="월 기준시간" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="note" placeholder="변경 사유·메모" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white sm:col-span-2">급여기준 추가</button></form>
      </section>
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">급여기준 이력</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3">직무</th><th>지점</th><th>적용기간</th><th>기본급</th><th>식대</th><th>고정연장</th><th>기타</th><th>상태</th></tr></thead><tbody>{rules.map(r=><tr key={v(r.id)} className="border-b border-slate-100"><td className="px-4 py-3 font-bold">{v(r.job_name)}</td><td>{v(r.site_name)||"공통"}</td><td>{v(r.effective_from)} ~ {v(r.effective_to)||"현재"}</td><td>{won(r.base_salary)}</td><td>{won(r.meal_allowance)}</td><td>{won(r.fixed_overtime_allowance)}</td><td>{won(r.other_allowance)}</td><td>{v(r.status)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
