import { NextRequest } from "next/server";
import ExcelJS from "exceljs";
import { currentUser } from "@/lib/auth";
import { withDatabase } from "@/lib/database";

type Row=Record<string,unknown>;
const q=(sql:string,...params:unknown[])=>withDatabase(db=>db.prepare(sql).all(...params) as Row[]);
function rows(kind:string,month:string){
if(kind==="workers") return q(`SELECT w.employee_no 사번,w.name 성명,w.status 상태,w.joined_at 입사일,w.left_at 퇴사일,w.phone 연락처,s.name 지점,j.name 직무 FROM app_workers w LEFT JOIN app_assignments a ON a.worker_id=w.id AND a.status='활성' LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id ORDER BY w.name`);
if(kind==="attendance") return q(`SELECT e.work_date 날짜,w.employee_no 사번,w.name 성명,s.name 지점,e.event_type 유형,e.minutes 분,e.days 일수,e.note 비고 FROM app_attendance_events e JOIN app_workers w ON w.id=e.worker_id LEFT JOIN app_sites s ON s.id=e.site_id WHERE substr(e.work_date,1,7)=? ORDER BY e.work_date,w.name`,month);
if(kind==="leave") return q(`SELECT l.event_date 날짜,w.employee_no 사번,w.name 성명,l.event_type 유형,l.leave_days 일수,l.note 비고 FROM app_leave_ledger l JOIN app_workers w ON w.id=l.worker_id ORDER BY l.event_date,w.name`);
if(kind==="payroll") return q(`SELECT r.payroll_month 급여월,w.employee_no 사번,w.name 성명,s.name 지점,j.name 직무,i.worked_days 근무일수,i.base_current 기본급,i.meal_current 식대,i.overtime_pay 연장수당,i.holiday_pay 휴일수당,i.night_pay 야간수당,i.leave_pay 연차수당,i.incentive 인센티브,i.retroactive_pay 소급지급,i.other_pay 기타지급,i.other_deduction 기타공제,i.manual_adjustment 수동조정,i.gross_pay 지급총액,i.review_status 검토상태 FROM app_payroll_items i JOIN app_payroll_runs r ON r.id=i.payroll_run_id JOIN app_workers w ON w.id=i.worker_id LEFT JOIN app_assignments a ON a.id=i.assignment_id LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id WHERE r.payroll_month=? ORDER BY s.name,w.name`,month);
if(kind==="billing") return q(`SELECT r.billing_month 청구월,w.employee_no 사번,w.name 성명,s.name 지점,j.name 직무,i.payroll_gross 급여총액,i.pension 국민연금,i.health 건강보험,i.long_term_care 장기요양,i.employment 고용보험,i.industrial_accident 산재보험,i.management_fee 관리비,i.profit 이윤,i.supply_amount 공급가액,i.vat 부가세,i.total_amount 총청구액,i.review_status 검토상태 FROM app_billing_items i JOIN app_billing_runs r ON r.id=i.billing_run_id JOIN app_workers w ON w.id=i.worker_id LEFT JOIN app_payroll_items p ON p.id=i.payroll_item_id LEFT JOIN app_assignments a ON a.id=p.assignment_id LEFT JOIN app_sites s ON s.id=a.site_id LEFT JOIN app_jobs j ON j.id=a.job_id WHERE r.billing_month=? ORDER BY s.name,w.name`,month);
if(kind==="sites") return q(`SELECT s.name 지점,s.site_type 유형,s.operation_status 상태,COUNT(DISTINCT CASE WHEN a.status='활성' THEN a.worker_id END) 재직인원,GROUP_CONCAT(DISTINCT j.name) 운영직무 FROM app_sites s LEFT JOIN app_assignments a ON a.site_id=s.id LEFT JOIN app_jobs j ON j.id=a.job_id GROUP BY s.id ORDER BY s.name`);
return null;}
export async function GET(request:NextRequest,{params}:{params:Promise<{kind:string}>}){const user=await currentUser();if(!user)return new Response("Unauthorized",{status:401});const{kind}=await params;const month=request.nextUrl.searchParams.get("month")||new Date().toISOString().slice(0,7);const data=rows(kind,month);if(!data)return new Response("Unknown export",{status:404});const workbook=new ExcelJS.Workbook();workbook.creator="Hansung Operations";const sheet=workbook.addWorksheet("data");if(data.length){const headers=Object.keys(data[0]);sheet.columns=headers.map(h=>({header:h,key:h,width:Math.min(30,Math.max(12,h.length*2+4))}));for(const row of data)sheet.addRow(row);sheet.getRow(1).font={bold:true};sheet.views=[{state:"frozen",ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:headers.length}};}else sheet.addRow(["데이터 없음"]);const buffer=await workbook.xlsx.writeBuffer();return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="hansung-${kind}-${month}.xlsx"`}});}
