"use client";

import { useMemo,useRef,useState } from "react";
import { completeOnboarding } from "@/app/onboarding/actions";

type Row=Record<string,unknown>;
type Props={sites:Row[];jobs:Row[];payRules:Row[]};
const steps=["기본정보","근무정보","계약","급여기준","입사서류"];
const input="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-500";
const v=(x:unknown)=>String(x??"");

export function OnboardingWizard({sites,jobs,payRules}:Props){
  const formRef=useRef<HTMLFormElement>(null);
  const [step,setStep]=useState(0),[maxStep,setMaxStep]=useState(0);
  const [siteId,setSiteId]=useState(""),[jobId,setJobId]=useState("");
  const filteredRules=useMemo(()=>payRules.filter(r=>v(r.job_id)===jobId&&(!r.site_id||v(r.site_id)===siteId)),[payRules,jobId,siteId]);
  const validateStep=(index:number)=>{const section=formRef.current?.querySelector(`[data-step="${index}"]`);const controls=section?.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>("input,select,textarea")??[];for(const control of controls){if(!control.checkValidity()){control.reportValidity();control.focus();return false;}}return true;};
  const next=()=>{if(!validateStep(step))return;const target=Math.min(steps.length-1,step+1);setMaxStep(m=>Math.max(m,target));setStep(target);};
  return <form ref={formRef} action={completeOnboarding} noValidate onSubmit={e=>{for(let i=0;i<steps.length;i++){if(!validateStep(i)){e.preventDefault();setStep(i);return;}}}} className="space-y-5">
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-5">{steps.map((label,i)=><button key={label} type="button" disabled={i>maxStep} onClick={()=>i<=maxStep&&setStep(i)} className={`rounded-xl border px-3 py-3 text-left disabled:cursor-not-allowed disabled:opacity-40 ${i===step?"border-teal-500 bg-teal-50":"border-slate-200 bg-white"}`}><p className="text-[11px] font-black text-slate-400">STEP {i+1}</p><p className={`mt-1 text-sm font-bold ${i===step?"text-teal-800":"text-slate-700"}`}>{label}</p></button>)}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600 transition-all" style={{width:`${((step+1)/steps.length)*100}%`}}/></div></div>

    <section data-step="0" className={`rounded-2xl border bg-white p-6 shadow-sm ${step===0?"block":"hidden"}`}><h2 className="text-xl font-black">1. 기본정보</h2><p className="mt-1 text-sm text-slate-500">인력 기준정보를 먼저 등록합니다.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-bold text-slate-500">성명 *<input name="name" required className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500">사번<input name="employee_no" className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500">연락처<input name="phone" className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500">이메일<input name="email" type="email" className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500">입사일 *<input name="joined_at" type="date" required className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500">생년월일<input name="birth_date" type="date" className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500 md:col-span-2">주소<input name="address" className={`${input} mt-1`}/></label></div></section>

    <section data-step="1" className={`rounded-2xl border bg-white p-6 shadow-sm ${step===1?"block":"hidden"}`}><h2 className="text-xl font-black">2. 근무정보</h2><p className="mt-1 text-sm text-slate-500">지점과 직무를 선택하면 다음 단계의 급여기준 후보가 자동으로 좁혀집니다.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs font-bold text-slate-500">지점 *<select name="site_id" required value={siteId} onChange={e=>setSiteId(e.target.value)} className={`${input} mt-1`}><option value="">지점 선택</option>{sites.map(x=><option key={v(x.id)} value={v(x.id)}>{v(x.name)}</option>)}</select></label><label className="text-xs font-bold text-slate-500">직무 *<select name="job_id" required value={jobId} onChange={e=>setJobId(e.target.value)} className={`${input} mt-1`}><option value="">직무 선택</option>{jobs.map(x=><option key={v(x.id)} value={v(x.id)}>{v(x.name)}</option>)}</select></label><label className="text-xs font-bold text-slate-500">근무형태<select name="work_type" className={`${input} mt-1`}><option>주중</option><option>스케줄</option><option>격주토</option><option>야간</option><option>기타</option></select></label><label className="text-xs font-bold text-slate-500">배치 메모<input name="assignment_note" className={`${input} mt-1`}/></label></div></section>

    <section data-step="2" className={`rounded-2xl border bg-white p-6 shadow-sm ${step===2?"block":"hidden"}`}><h2 className="text-xl font-black">3. 계약</h2><p className="mt-1 text-sm text-slate-500">최초 계약기간을 등록합니다.</p><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-xs font-bold text-slate-500">계약 시작일 *<input name="contract_started_at" type="date" required className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500">계약 종료일 *<input name="contract_ended_at" type="date" required className={`${input} mt-1`}/></label><label className="text-xs font-bold text-slate-500">계약 메모<input name="contract_note" className={`${input} mt-1`}/></label></div></section>

    <section data-step="3" className={`rounded-2xl border bg-white p-6 shadow-sm ${step===3?"block":"hidden"}`}><h2 className="text-xl font-black">4. 급여기준</h2><p className="mt-1 text-sm text-slate-500">선택한 지점·직무와 맞는 적용 급여기준만 표시합니다. 없으면 미선택 상태로 등록할 수 있습니다.</p><div className="mt-5"><select name="pay_rule_id" className={input}><option value="">급여기준 미선택 — 이후 확인필요 처리</option>{filteredRules.map(x=><option key={v(x.id)} value={v(x.id)}>{v(x.job_name)} · {Number(x.base_salary??0).toLocaleString("ko-KR")}원 · {v(x.effective_from)}{x.site_id?" · 지점전용":" · 공통"}</option>)}</select>{jobId&&filteredRules.length===0?<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-800">선택한 조건에 맞는 급여기준이 없습니다. 입사 등록은 가능하지만 급여 생성 전 기준 연결이 필요합니다.</p>:null}</div></section>

    <section data-step="4" className={`rounded-2xl border bg-white p-6 shadow-sm ${step===4?"block":"hidden"}`}><h2 className="text-xl font-black">5. 입사서류</h2><p className="mt-1 text-sm text-slate-500">현재 확보된 서류를 체크하고 최종 등록합니다. 미체크 항목도 이후 문서 메뉴에서 처리할 수 있습니다.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["contract_document","근로계약서"],["privacy_document","개인정보동의"],["dispatch_document","파견 관련 서류"],["onboarding_document","입사 안내"]].map(([name,label])=><label key={name} className="flex min-h-20 items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm font-bold"><input name={name} type="checkbox" className="size-4"/>{label}</label>)}</div><label className="mt-4 block text-xs font-bold text-slate-500">입사 관련 메모<textarea name="note" className="mt-1 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label></section>

    <div className="sticky bottom-4 flex items-center justify-between rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><button type="button" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-bold disabled:opacity-30">이전</button><div className="text-center"><p className="text-xs font-bold text-slate-400">{step+1} / {steps.length}</p><p className="text-sm font-black text-slate-800">{steps[step]}</p></div>{step<steps.length-1?<button type="button" onClick={next} className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white">다음</button>:<button className="rounded-xl bg-teal-700 px-6 py-2.5 text-sm font-bold text-white">입사 등록 완료</button>}</div>
  </form>;
}
